ocaml_binary(
    name='main',
    bytecode_only = True,
    srcs=[
        'main.ml',
        'CLI.ml',
        'CLI.mli',
    ],
    compiler_flags = [
        "-package angstrom",
    ],
#    compiler_flags = [
#        "-warn-error",
#        "+a",
#    ],
)
